# k8s/service.yaml

# --- Backend Service (Internal) ---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    component: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

# --- Frontend Service (External/Public) ---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80