# .github/workflows/deploy.yml

name: Deploy MERN App to EKS

on:
  push:
    branches: [ "main" ] 

env:
  AWS_REGION: ap-south-1 
  EKS_CLUSTER_NAME: EKS-Saikrishna1
  BACKEND_IMAGE_NAME: ipl-backend
  FRONTEND_IMAGE_NAME: ipl-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push backend image
      uses: docker/build-push-action@v4
      with:
        
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.BACKEND_IMAGE_NAME }}:latest

    - name: Build and push frontend image
      uses: docker/build-push-action@v4
      with:
        
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.FRONTEND_IMAGE_NAME }}:latest

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        
        echo "Restarting deployments to pull the latest image..."
        kubectl rollout restart deployment backend-deployment
        kubectl rollout restart deployment frontend-deployment